### ISSUE TITLE
Nested and/or's

### ISSUE THREAD

**Issue by MilesHart** [Galbar/JsonPath-PHP#29]
I'm nesting a set of and's and or's. I seeing others are also querying similar issues. Can someone help:-

I've formatted the query for ease of reading.

$.parent[?((@.podh_cpf_action == 'Delivered – Left in Plot' or @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)') and (@.podh_cpf_reason_not_ready == 'Already completed' or @.podh_cpf_reason_not_ready == 'No access to plot' or @.podh_cpf_reason_not_ready == 'No access to site' or @.podh_cpf_reason_not_ready == 'Plot not ready' or @.podh_cpf_reason_not_ready == 'Not required by site'))]

It seems to be returning different results if I switch the two outer or's, which logically they should produce the same results.

Thank you for any help.

Milo

**Comment by Galbar** [comment]
Hi @MilesHart ,

If you look at the language specification in the README.md it says:
>__Limitations__ on the specification:  
>* The jsonpath inside _value_ cannot contain `or`, `and` or any comparator.

More over, the language specification (of this implementation) says:
>filterexpr  = '?(' ors ')'
>
>ors         = ands (' or ' ands)*
>ands        = expr (' and ' expr)*
>expr        = 'not'? (value | comp)
>comp        = value ('==' | '!=' | '<' | '>' | '<=' | '>=' | '=~') value
>value       = (jsonpath | childpath | number | string | boolean | regpattern | null | length)
>length      = (jsonpath | childpath) '.length'

Which means that you can not have parenthesis `()` grouping expressions inside the filter expression.

This was done like this because having recursive expressions is added complexity and the current behavior was more than enough for my use case.

Regarding your query, it should work if you flatten it out:
```
$.parent[?(
    @.podh_cpf_action == 'Delivered – Left in Plot' and @.podh_cpf_reason_not_ready == 'Already completed'
    or
    @.podh_cpf_action == 'Delivered – Left in Plot' and @.podh_cpf_reason_not_ready == 'No access to plot'
    or
    @.podh_cpf_action == 'Delivered – Left in Plot' and @.podh_cpf_reason_not_ready == 'No access to site'
    or
    @.podh_cpf_action == 'Delivered – Left in Plot' and @.podh_cpf_reason_not_ready == 'Plot not ready'
    or
    @.podh_cpf_action == 'Delivered – Left in Plot' and @.podh_cpf_reason_not_ready == 'Not required by site'
    or
    @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)' and @.podh_cpf_reason_not_ready == 'Already completed'
    or
    @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)' and @.podh_cpf_reason_not_ready == 'No access to plot'
    or
    @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)' and @.podh_cpf_reason_not_ready == 'No access to site'
    or
    @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)' and @.podh_cpf_reason_not_ready == 'Plot not ready'
    or
    @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)' and @.podh_cpf_reason_not_ready == 'Not required by site'
)]
```

You could also do something like (I didn't try running it but you get the idea :wink: ):
```php
$partialResult = $jsonObj->get("$.parent[?((@.podh_cpf_action == 'Delivered – Left in Plot' or @.podh_cpf_action == 'Delivered – Left on Site (not in Plot)'))]");
$finalResult = new JsonObject($partialResult)->get("$[?(@.podh_cpf_reason_not_ready == 'Already completed' or @.podh_cpf_reason_not_ready == 'No access to plot' or @.podh_cpf_reason_not_ready == 'No access to site' or @.podh_cpf_reason_not_ready == 'Plot not ready' or @.podh_cpf_reason_not_ready == 'Not required by site')]");
```

Hope this helps :smile:

**Comment by MilesHart** [comment]
@Galbar Thank you so much for your quick response. I thought that was the case, thank you for clarifying.

As a sidebar, do you have example of the following in the documentation?

```
namelist    = var_name (',' (var_name | '\'' .*? '\'' | '"' .*? '"'))*
indexlist   = index (',' index)*
arrayslice  = index? ':' index? ':' index?
filterexpr  = '?(' ors ')'
```

Ace job
