### ISSUE TITLE
Absence of getArray() function

### ISSUE THREAD

**Issue by khageshsaini** [Galbar/JsonPath-PHP#30]
There is no function `getArray()` present in `JsonObject` class.  All the subsequent usage of this function result in error.

https://github.com/Galbar/JsonPath-PHP/blob/3820fd4da177f5cf180aa47260d57086e4e4ba29/src/Galbar/JsonPath/JsonObject.php#L67-L70

It should be included in the class or the usage of this function in readme should be stripped off.

**Comment by Galbar** [comment]
Hi @khageshsaini, nice catch!
Actually the function `getValue()` does exist and does exactly that.

This function, on the other hand may be interesting when #24 is done, as the internal representation will not be an array and therefore `getValue()` would make no sense to have (what value? the object representation? the array representation? the internal representation? etc.)

As of this issue, I'd say use `getValue()` for now. I'll update the docs changing `getArray()` for `getValue()`.

**Comment by Galbar** [comment]
Closing this as it is not a real issue with the current implementation, just docs being wrong (which are fixed now)
