### ISSUE TITLE
Returning parent objects - query select from a child

### ISSUE THREAD

**Issue by MilesHart** [Galbar/JsonPath-PHP#36]
I have data with parent/child nested object (similar to the store and books example)..

Is it possible to return the parent object??

e.g.

$..book[?(@.category == 'fiction')]

returns all the books with category of fiction. I want to return the store object. So inessence.

Return me all the stores that have a book of category fiction.

**Comment by Galbar** [comment]
To me it looks like you are looking for something like this:  
`$[?(@.*[?(@.category == "fiction")].length > 0)]`

PD: Sorry for late answer :/

**Comment by Galbar** [comment]
Hi @MilesHart, did this solve your question? can this be closed?
