### ISSUE TITLE
Would you please release a new stable package?

### ISSUE THREAD

**Issue by TheNorthMemory** [Galbar/JsonPath-PHP#40]
Hello,

I found this package via packagist, it was the stable version 1.0 on there. Currently, the `dev-master` were maintains the `.length` feature, would you please release a new stable version on packagist?

**Comment by keywan-ghadami** [comment]
I found myself also https://github.com/FlowCommunications/JSONPath
wich is also available in packagist
https://packagist.org/packages/flow/jsonpath
and alternative language https://github.com/jmespath/jmespath.php
that looks also promising.

**Comment by TheNorthMemory** [comment]
Yes, I'd tried use [jmespath.php](https://github.com/jmespath/jmespath.php), it's good, but just had the get/fetch. 

And [FlowCommunications/JSONPath](https://github.com/FlowCommunications/JSONPath) was wrote those comments:

> [Galbar/JsonPath-PHP](https://github.com/Galbar/JsonPath-PHP) is a PHP implementation that does a few things this project doesn't and is a strong alternative

This JsonPath is so good so that should be a new stable release here.

**Comment by Galbar** [comment]
@TheNorthMemory I forgot to do the release when I merged that! I'm doing it now. :smile:

**Comment by Galbar** [comment]
Ok, I've created the release. Please open a new issue if you find any issues with 1.1 :smile:
