### ISSUE TITLE
support && and || as logical operators

### ISSUE THREAD

**Issue by bwl21** [Galbar/JsonPath-PHP#44]
as https://extendsclass.com/jsonpath-tester.html supports && and || operators, it would be great if JsonPath-PHP could do the same.

see #37.

**Comment by Galbar** [comment]
So I was checking the code to see how simple would it be to do this. Turns out it was hyper simple. Can you double check if the PR #45 looks like what you meant?

Cheers

**Comment by Galbar** [comment]
I just published version 1.2 with this changes
