### ISSUE TITLE
Length operator now returning array instead of number (after switching to 1.3)

### ISSUE THREAD

**Issue by baohx2000** [Galbar/JsonPath-PHP#53]
On upgrading from 1.2 to 1.3, quite a few of our tests broke since the `.length` query now seems to return an array with the length in most cases instead of the raw count.

**Comment by Galbar** [comment]
Oops! My bad! I just checked and it looks like at some point I changed the behavior of `.length` and then forgot about the breaking change!

`.length` now works as all other queries: returns an array with the results, unless smartGet is set to true, then it returns the actual result, if the path does not diverge.

This is a breaking change and I should have published it in a different major version. My bad.

I'll revert that change ASAP and publish a new patch version.

Sorry for the inconveniences!

**Comment by Galbar** [comment]
I've created release `1.3.1` that should work as expected. Please, let me know if there's any other issues you may find

**Comment by baohx2000** [comment]
Thanks for the super fast turnaround!

**Comment by Galbar** [comment]
It was an easy one. Also, I kind of hate breaking SemVer :sweat_smile:
