### ISSUE TITLE
Compatibility with json-ld

### ISSUE THREAD

**Issue by nicoren-tangkoko** [Galbar/JsonPath-PHP#56]
Hi, in first thank you for your work.

### Context :
I am using a rest web service returning json-ld returning following response : 

`{
    "@context": "/api/contexts/Datarow",
    "@id": "/api/v1/datasets/27910054-d705-4d5d-8dd9-01929175f4b6/rows",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/api/v1/row/e4aa9627-68a1-4bf6-ba04-3256d2e96e29",
            "@type": "Datarow",
            "id": "e4aa9627-68a1-4bf6-ba04-3256d2e96e29",
            "rowData": {
                "IDOC": {
                    "E1OCLFM": {
                        "OBTAB": "MARA",
                        "OBJEK": "12289LK",
                        "ZMATNR": "12289LK",
                        "KLART": "001",
                        "E1AUSPM": [
                            {
                                "ATNAM": "LAVPF01001",
                                "ATWRT": "L1",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "Almanachs",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Catégorie"
                                },
                                "E1CAWNM": {
                                    "SPRAS": "F",
                                    "ATWTB": "Almanachs"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01001",
                                "ATWRT": "L2",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "Qualité BRONZE",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Catégorie"
                                },
                                "E1CAWNM": {
                                    "SPRAS": "F",
                                    "ATWTB": "Qualité BRONZE"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01002",
                                "ATWRT": "",
                                "ATFLV": "5",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Stock Alerte"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01003",
                                "ATWRT": "",
                                "ATFLV": "30",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Quantité alerte"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01012",
                                "ATWRT": "JL122-422-A",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "image"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01012",
                                "ATWRT": "JL122-422-B",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "image"
                                }
                            },
                            {
                                "ATNAM": "PEFC_GLOBALE",
                                "ATWRT": "1304",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": [
                                    {
                                        "SPRAS": "F",
                                        "ATBEZ": "Certifié PEFC 100%"
                                    },
                                    {
                                        "SPRAS": "I",
                                        "ATBEZ": "certificati PEFC 100%"
                                    },
                                    {
                                        "SPRAS": "N",
                                        "ATBEZ": "100% PEFC gecertificeerd"
                                    },
                                    {
                                        "SPRAS": "E",
                                        "ATBEZ": "100% PEFC certified"
                                    },
                                    {
                                        "SPRAS": "D",
                                        "ATBEZ": "PEFC zertifiziert 100%"
                                    },
                                    {
                                        "SPRAS": "S",
                                        "ATBEZ": "100% PEFC Certificado"
                                    },
                                    {
                                        "SPRAS": "L",
                                        "ATBEZ": "100% certyfikat PEFC"
                                    },
                                    {
                                        "SPRAS": "K",
                                        "ATBEZ": "100% PEFC certificeret"
                                    },
                                    {
                                        "SPRAS": "V",
                                        "ATBEZ": "100% PEFC certifierad"
                                    },
                                    {
                                        "SPRAS": "U",
                                        "ATBEZ": "100% PEFC-sertifioitu"
                                    },
                                    {
                                        "SPRAS": "O",
                                        "ATBEZ": "100% PEFC certificeret"
                                    },
                                    {
                                        "SPRAS": "",
                                        "ATBEZ": "Gramaj"
                                    },
                                    {
                                        "SPRAS": "T",
                                        "ATBEZ": "PEFC sertifikalı% 100"
                                    }
                                ]
                            }
                        ]
                    }
                }
            },
            "originalData": "<IDOC><E1OCLFM><OBTAB>MARA</OBTAB><OBJEK>12289LK</OBJEK><ZMATNR>12289LK</ZMATNR><KLART>001</KLART><E1AUSPM><ATNAM>LAVPF01001</ATNAM><ATWRT>L1</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB>Almanachs</ATWTB><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Catégorie</ATBEZ></E1CABTM><E1CAWNM><SPRAS>F</SPRAS><ATWTB>Almanachs</ATWTB></E1CAWNM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01001</ATNAM><ATWRT>L2</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB>Qualité BRONZE</ATWTB><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Catégorie</ATBEZ></E1CABTM><E1CAWNM><SPRAS>F</SPRAS><ATWTB>Qualité BRONZE</ATWTB></E1CAWNM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01002</ATNAM><ATWRT/><ATFLV>5</ATFLV><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Stock Alerte</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01003</ATNAM><ATWRT/><ATFLV>30</ATFLV><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Quantité alerte</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01012</ATNAM><ATWRT>JL122-422-A</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>image</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01012</ATNAM><ATWRT>JL122-422-B</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>image</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>PEFC_GLOBALE</ATNAM><ATWRT>1304</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Certifié PEFC 100%</ATBEZ></E1CABTM><E1CABTM><SPRAS>I</SPRAS><ATBEZ>certificati PEFC 100%</ATBEZ></E1CABTM><E1CABTM><SPRAS>N</SPRAS><ATBEZ>100% PEFC gecertificeerd</ATBEZ></E1CABTM><E1CABTM><SPRAS>E</SPRAS><ATBEZ>100% PEFC certified</ATBEZ></E1CABTM><E1CABTM><SPRAS>D</SPRAS><ATBEZ>PEFC zertifiziert 100%</ATBEZ></E1CABTM><E1CABTM><SPRAS>S</SPRAS><ATBEZ>100% PEFC Certificado</ATBEZ></E1CABTM><E1CABTM><SPRAS>L</SPRAS><ATBEZ>100% certyfikat PEFC</ATBEZ></E1CABTM><E1CABTM><SPRAS>K</SPRAS><ATBEZ>100% PEFC certificeret</ATBEZ></E1CABTM><E1CABTM><SPRAS>V</SPRAS><ATBEZ>100% PEFC certifierad</ATBEZ></E1CABTM><E1CABTM><SPRAS>U</SPRAS><ATBEZ>100% PEFC-sertifioitu</ATBEZ></E1CABTM><E1CABTM><SPRAS>O</SPRAS><ATBEZ>100% PEFC certificeret</ATBEZ></E1CABTM><E1CABTM><SPRAS/><ATBEZ>Gramaj</ATBEZ></E1CABTM><E1CABTM><SPRAS>T</SPRAS><ATBEZ>PEFC sertifikalı% 100</ATBEZ></E1CABTM></E1AUSPM></E1OCLFM></IDOC>",
            "datasetId": "27910054-d705-4d5d-8dd9-01929175f4b6"
        },
        {
            "@id": "/api/v1/row/e4aa9627-68a1-4bf6-ba04-3256d2e96e29",
            "@type": "Datarow",
            "id": "e4aa9627-68a1-4bf6-ba04-3256d2e96e29",
            "rowData": {
                "IDOC": {
                    "E1OCLFM": {
                        "OBTAB": "MARA",
                        "OBJEK": "12289LK",
                        "ZMATNR": "12289LK",
                        "KLART": "001",
                        "E1AUSPM": [
                            {
                                "ATNAM": "LAVPF01001",
                                "ATWRT": "L1",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "Almanachs",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Catégorie"
                                },
                                "E1CAWNM": {
                                    "SPRAS": "F",
                                    "ATWTB": "Almanachs"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01001",
                                "ATWRT": "L2",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "Qualité BRONZE",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Catégorie"
                                },
                                "E1CAWNM": {
                                    "SPRAS": "F",
                                    "ATWTB": "Qualité BRONZE"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01002",
                                "ATWRT": "",
                                "ATFLV": "5",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Stock Alerte"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01003",
                                "ATWRT": "",
                                "ATFLV": "30",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "Quantité alerte"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01012",
                                "ATWRT": "JL122-422-A",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "image"
                                }
                            },
                            {
                                "ATNAM": "LAVPF01012",
                                "ATWRT": "JL122-422-B",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": {
                                    "SPRAS": "F",
                                    "ATBEZ": "image"
                                }
                            },
                            {
                                "ATNAM": "PEFC_GLOBALE",
                                "ATWRT": "1304",
                                "ATFLV": "",
                                "ATFLB": "0",
                                "ATWTB": "",
                                "E1CABTM": [
                                    {
                                        "SPRAS": "F",
                                        "ATBEZ": "Certifié PEFC 100%"
                                    },
                                    {
                                        "SPRAS": "I",
                                        "ATBEZ": "certificati PEFC 100%"
                                    },
                                    {
                                        "SPRAS": "N",
                                        "ATBEZ": "100% PEFC gecertificeerd"
                                    },
                                    {
                                        "SPRAS": "E",
                                        "ATBEZ": "100% PEFC certified"
                                    },
                                    {
                                        "SPRAS": "D",
                                        "ATBEZ": "PEFC zertifiziert 100%"
                                    },
                                    {
                                        "SPRAS": "S",
                                        "ATBEZ": "100% PEFC Certificado"
                                    },
                                    {
                                        "SPRAS": "L",
                                        "ATBEZ": "100% certyfikat PEFC"
                                    },
                                    {
                                        "SPRAS": "K",
                                        "ATBEZ": "100% PEFC certificeret"
                                    },
                                    {
                                        "SPRAS": "V",
                                        "ATBEZ": "100% PEFC certifierad"
                                    },
                                    {
                                        "SPRAS": "U",
                                        "ATBEZ": "100% PEFC-sertifioitu"
                                    },
                                    {
                                        "SPRAS": "O",
                                        "ATBEZ": "100% PEFC certificeret"
                                    },
                                    {
                                        "SPRAS": "",
                                        "ATBEZ": "Gramaj"
                                    },
                                    {
                                        "SPRAS": "T",
                                        "ATBEZ": "PEFC sertifikalı% 100"
                                    }
                                ]
                            }
                        ]
                    }
                }
            },
            "originalData": "<IDOC><E1OCLFM><OBTAB>MARA</OBTAB><OBJEK>12289LK</OBJEK><ZMATNR>12289LK</ZMATNR><KLART>001</KLART><E1AUSPM><ATNAM>LAVPF01001</ATNAM><ATWRT>L1</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB>Almanachs</ATWTB><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Catégorie</ATBEZ></E1CABTM><E1CAWNM><SPRAS>F</SPRAS><ATWTB>Almanachs</ATWTB></E1CAWNM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01001</ATNAM><ATWRT>L2</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB>Qualité BRONZE</ATWTB><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Catégorie</ATBEZ></E1CABTM><E1CAWNM><SPRAS>F</SPRAS><ATWTB>Qualité BRONZE</ATWTB></E1CAWNM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01002</ATNAM><ATWRT/><ATFLV>5</ATFLV><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Stock Alerte</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01003</ATNAM><ATWRT/><ATFLV>30</ATFLV><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Quantité alerte</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01012</ATNAM><ATWRT>JL122-422-A</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>image</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>LAVPF01012</ATNAM><ATWRT>JL122-422-B</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>image</ATBEZ></E1CABTM></E1AUSPM><E1AUSPM><ATNAM>PEFC_GLOBALE</ATNAM><ATWRT>1304</ATWRT><ATFLV/><ATFLB>0</ATFLB><ATWTB/><E1CABTM><SPRAS>F</SPRAS><ATBEZ>Certifié PEFC 100%</ATBEZ></E1CABTM><E1CABTM><SPRAS>I</SPRAS><ATBEZ>certificati PEFC 100%</ATBEZ></E1CABTM><E1CABTM><SPRAS>N</SPRAS><ATBEZ>100% PEFC gecertificeerd</ATBEZ></E1CABTM><E1CABTM><SPRAS>E</SPRAS><ATBEZ>100% PEFC certified</ATBEZ></E1CABTM><E1CABTM><SPRAS>D</SPRAS><ATBEZ>PEFC zertifiziert 100%</ATBEZ></E1CABTM><E1CABTM><SPRAS>S</SPRAS><ATBEZ>100% PEFC Certificado</ATBEZ></E1CABTM><E1CABTM><SPRAS>L</SPRAS><ATBEZ>100% certyfikat PEFC</ATBEZ></E1CABTM><E1CABTM><SPRAS>K</SPRAS><ATBEZ>100% PEFC certificeret</ATBEZ></E1CABTM><E1CABTM><SPRAS>V</SPRAS><ATBEZ>100% PEFC certifierad</ATBEZ></E1CABTM><E1CABTM><SPRAS>U</SPRAS><ATBEZ>100% PEFC-sertifioitu</ATBEZ></E1CABTM><E1CABTM><SPRAS>O</SPRAS><ATBEZ>100% PEFC certificeret</ATBEZ></E1CABTM><E1CABTM><SPRAS/><ATBEZ>Gramaj</ATBEZ></E1CABTM><E1CABTM><SPRAS>T</SPRAS><ATBEZ>PEFC sertifikalı% 100</ATBEZ></E1CABTM></E1AUSPM></E1OCLFM></IDOC>",
            "datasetId": "27910054-d705-4d5d-8dd9-01929175f4b6"
        }
    ],
    "hydra:totalItems": 1000,
    "hydra:view": {
        "@id": "/api/v1/datasets/27910054-d705-4d5d-8dd9-01929175f4b6/rows?itemsPerPage=2&page=1",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "/api/v1/datasets/27910054-d705-4d5d-8dd9-01929175f4b6/rows?itemsPerPage=2&page=1",
        "hydra:last": "/api/v1/datasets/27910054-d705-4d5d-8dd9-01929175f4b6/rows?itemsPerPage=2&page=500",
        "hydra:next": "/api/v1/datasets/27910054-d705-4d5d-8dd9-01929175f4b6/rows?itemsPerPage=2&page=2"
    }
}`

I am trying to retrieve very child of  "hydra:member" node using json path but the ":" char seems not to be in the CHILD_NAME regexp. 

### Step to reproduce :
execute following code : 
`
$jsonObject = new JsonObject($rawData);
$items = $jsonObject->getJsonObjects("$.hydra:member[*]");
`
### Expected result
$items should contain every chold node of hydra:member.

### Actual Result
items is equal to false

Best regards

**Comment by Galbar** [comment]
For non-valid javascript variable names, you can use the `[]` notation: `$['hydra:member'][*]`.

FYI, you can avoid the final `[*]` with any of these two options:
Normal:
```php
$jsonObject = new JsonObject($rawData);
$results = $jsonObject->getJsonObjects("$['hydra:member']");
if ($result === false) {
    echo "field not found"
}
$items = $result[0];
```
Using [_smartGet_](https://github.com/Galbar/JsonPath-PHP#smartget):
```php
$jsonObject = new JsonObject($rawData, true); // Enable smartGet functionality
$items = $jsonObject->getJsonObjects("$['hydra:member']");
if ($items === false) {
    echo "field not found"
}
```

In either case `$items` will contain the same result and the jsonPath query will run faster.

**Comment by nicoren-tangkoko** [comment]
I close this issue. Thank you again.
