### ISSUE TITLE
Whitespaces in jsonPath

### ISSUE THREAD

**Issue by oschwier** [Galbar/JsonPath-PHP#61]
What can I do if there are whitespaces within the jsonPath?

Path looks like:

```$.Technische Daten.Abmessungen```

```php
$res = new JsonObject(myJSONstring);
$res = $res->get($jsonPath);
```

returns false

Debug Output:
```php
JsonPath::subtreeGet(array('Technische Daten' => array('Abmessungen' => array('Breite in mm' => '300', 'Tiefe in mm' => '580', 'Höhe in mm' => '715', 'Gewicht' => '60 kg'),....
```

**Comment by Galbar** [comment]
Hi @oschwier, this seems to be a duplicate of #42.

Could check if the solution works for you and, if that is the case, close this issue?

If that doesn't fix it for you, let me know

**Comment by oschwier** [comment]
Ah sorry, missed that issue! Seams to work! Thanks for the quick response!
