### ISSUE TITLE
Support for keys with colons

### ISSUE THREAD

**Issue by tbreuss** [Galbar/JsonPath-PHP#66]
It seems like keys containing colons do not work:

~~~php
$data = [
    'a:1' => [
        'b:2' => 'This is a:1 > b:2',
    ]
];

$jsonObject = new \JsonPath\JsonObject($data);
var_dump($jsonObject->get('$.a:1.b:2'));

// Output:
// array(0) { }
~~~

Is this the expected behaviour?

I'm asking since I'm looking for an alternative for Peekmo\JsonPath, which is not maintained anymore. With his implementation colons within keys are supported. We are using them for a kind of namespaced json.

~~~php
$jsonPath = new \Peekmo\JsonPath\JsonStore($data);
var_dump($jsonPath->get('$.a:1.b:2'));

// Output:
// array(1) { [0]=> &string(17) "This is a:1 > b:2" }
~~~

**Comment by Galbar** [comment]
Hi @tbreuss,

As the Readme says, the dot-notation only supports variable names following this pattern: `var_name = /^\.([\p{L}\p{N}\_\$][\p{L}\p{N}\_\-\$]*|\*)(.*)/u`, which roughly translates to "any valid JavaScript variable name", plus some quirks such as names starting with numbers or containing dashes (`-`).

To access properties with names that don't follow that pattern, the solution is to use `$['a:1']`. Similar to the dot-notation, they can be chained: `$['a:1']["b:2"]`.

Let me know if that solves your issue,
Cheers!

**Comment by tbreuss** [comment]
> To access properties with names that don't follow that pattern, the solution is to use `$['a:1']`. Similar to the dot-notation, they can be chained: `$['a:1']["b:2"]`.

I just tried your suggestion and it works:

~~~php

$jsonObject = new \JsonPath\JsonObject($data);
var_dump($jsonObject->get('$["a:1"]["b:2"]'));

// Output
// array(1) { [0]=> &string(17) "This is a:1 > b:2" }

~~~

So, thanks for your reply and sorry for bothering you with my RTFM question.
